# Generated by Django 4.2.20 on 2026-01-27 17:54

from django.db import migrations, models
import idc.models


class Migration(migrations.Migration):

    dependencies = [
        ('idc', '0002_user_data'),
    ]

    operations = [
        migrations.CreateModel(
            name='SharedCart',
            fields=[
                ('cart_id', models.CharField(default=idc.models.cart_keygen, max_length=64, primary_key=True, serialize=False)),
                ('source_ip', models.GenericIPAddressField(default='0.0.0.0')),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('definition', models.TextField(default='{}')),
                ('series_ids', models.TextField(default='')),
            ],
        ),
    ]
