# Generated by Django 4.2.20 on 2026-02-25 17:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('idc_collections', '0018_alter_collection_collection_type'),
        ('idc', '0003_sharedcart'),
    ]

    operations = [
        migrations.AddField(
            model_name='sharedcart',
            name='idc_version',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='idc_collections.imagingdatacommonsversion'),
        ),
    ]
