# Generated by Django 4.2.30 on 2026-09-21 23:41

from django.db import migrations, models
import idc.models


class Migration(migrations.Migration):

    dependencies = [
        ('idc', '0004_sharedcart_idc_version'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sharedcart',
            name='cart_id',
            field=models.CharField(default=idc.models.cart_keygen, max_length=255, primary_key=True, serialize=False),
        ),
    ]
